config/routes.rb
Rails.application.routes.draw do

  root 	'pages#home'
 	get 	'pages/about'
  get 	'pages/contact'

  devise_for :users, :controllers => { :registrations => :registrations }

  resources :organizations
  resources :work_fields
  resources :degres
  resources :institutes
  resources :cities
  resources :users do
  	resources :userinfos
  	resources :educations
	  resources :experiences
  end
  resources :advertises do
  	resources :jobs
	end



end

app/models/advertise.rb
class Advertise < ActiveRecord::Base
  belongs_to :user
  has_many :jobs, dependent: :destroy

  has_attached_file :image, :styles => { :medium => "500x500" }, 
  																				:default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  
end

app/models/city.rb
class City < ActiveRecord::Base
	has_many :institutes
	has_many :jobs
end

app/models/degre.rb
class Degre < ActiveRecord::Base
	has_many :educations
	has_many :jobs
	
  def name_with_type
   "#{name} #{drege_type}"
  end
end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :user
  belongs_to :degre
  belongs_to :institute
  
  validates :division, 				presence: true
  validates :obtained_marks, 	presence: true
  validates :pass_year, 			presence: true
  validates :degre_id, 				presence: true
  validates :institute_id, 		presence: true
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :work_field
  belongs_to :user
  
  validates :work_type, 			presence: true
  validates :start_date, 			presence: true
  validates :end_date, 				presence: true
  validates :work_field_id, 	presence: true
end

app/models/institute.rb
class Institute < ActiveRecord::Base
  belongs_to :city
  has_many :educations
  
  def name_with_city
   "#{name} #{city.name}"
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :advertise
  belongs_to :work_field
  belongs_to :organization
  belongs_to :degre
  belongs_to :city
end

app/models/organization.rb
class Organization < ActiveRecord::Base
	has_many :jobs
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :userinfos
  has_many :educations
  has_many :experiences
  has_many :joblizeds


  has_attached_file :avatar, :styles => { :medium => "400x400>", :thumb => "100x100>" },
  																				:default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/userinfo.rb
class Userinfo < ActiveRecord::Base
  belongs_to :user
  validates :mobile, 		presence: true
  validates :address, 	presence: true
end

app/models/work_field.rb
class WorkField < ActiveRecord::Base
	has_many :experiences
	has_many :jobs
end

app/helpers/advertises_helper.rb
module AdvertisesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/degres_helper.rb
module DegresHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="col-md-12 alert alert-error alert-danger">
    <div class="col-md pull-right">
    <button type="button" class="close" data-dismiss="alert">x</button>
    </div>
    <h3>#{pluralize(resource.errors.count, "error")} prohibited this user being saved:</h3>
      <div class="col-md-12">
      #{messages}
      </div>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/userinfos_helper.rb
module UserinfosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_admin_penal.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% if logged_in_admin? %>
    <ol class="breadcrumb">
      <li><%= link_to 'Advertisment', advertises_path %></li>
      <li><%= link_to 'City', cities_path %></li>
      <li><%= link_to 'Degree', degres_path %></li>
      <li><%= link_to 'Institute', institutes_path %></li>
      <li><%= link_to 'Organization', organizations_path %></li>
      <li><%= link_to 'Work Field', work_fields_path %></li>
    </ol>
    <% end %>
  </div>
</div>

app/views/shared/_education.html.erb
<h3>Educations</h3>
<hr>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Division</th>
      <th>Obt: Marks</th>
      <th>Pass year</th>
      <th>Degree</th>
      <th>Institute</th>
    </tr>
  </thead>

  <tbody>
    <% @user.educations.each do |education| %>
      <tr>
        <td><%= education.division %></td>
        <td><%= education.obtained_marks %></td>
        <td><%= education.pass_year.strftime("%Y") %></td>
        <td><%= education.degre.name_with_type %></td>
        <td><%= education.institute.name_with_city %></td>
        <td><%= link_to "", edit_user_education_path(current_user, education),
                                            class: "glyphicon glyphicon-pencil" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@education.errors.count, "error") %> prohibited this education from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_experience.html.erb
<h3>Experiences</h3>
<hr>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Work type</th>
      <th>Work field</th>
      <th>Start date</th>
      <th>End date</th>
    </tr>
  </thead>

  <tbody>
    <% @user.experiences.each do |experience| %>
      <tr>
        <td><%= experience.work_type %></td>
        <td><%= experience.work_field.field_name %></td>
        <td><%= experience.start_date.strftime("%d-%m-%Y") %></td>
        <td><%= experience.end_date.strftime("%d-%m-%Y") %></td>
        <td><%= link_to "", edit_user_experience_path(current_user, experience),
                                                class: "glyphicon glyphicon-pencil" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top">
	<nav class="navbar navbar-default">
		<div class="container-fluid">
		  <div class="navbar-header">
		    <%= link_to 'Pak Apply', '/', class: "navbar-brand" %>
		  </div>
		    <ul class="nav navbar-nav">
		      <li class="active"><%= link_to "Home" ,root_url %></li>
		      <li><%= link_to "About", pages_about_path %></li>
		      <li><%= link_to 'Contact', pages_contact_path %></li>
		      <li><%= link_to 'Jobs', advertises_path %></li>
		    </ul>
		    <ul class="nav navbar-nav navbar-right">
		    	<% if user_signed_in? %>
						<li><%= avatar(@user) %></li>
						<li><%= link_to "#{@user.first_name} #{@user.last_name}", current_user %></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"
								role="button" aria-haspopup="true" aria-expanded="false">
								Account
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to 'Profile', current_user %></li>
								<li><%= link_to 'Setting', edit_user_registration_path %></li>
								<li><%= link_to 'Privercy' %></li>
								<li role="separator" class="divider"></li>
								<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
					    </ul>
					  </li>
		    	<% else %>
						<li><%= link_to 'Sign Up', new_user_registration_path %></li>
						<li><%= link_to 'Log In', new_user_session_path %></li>
		      <% end %>
		    </ul>
		</div>
	</nav>
</header>

app/views/shared/_job_list.html.erb
<% @advertise.jobs.each do |job| %>
	<div class="panel panel-default">
		<div class="panel-heading"><strong>Job Title:</strong> <%= job.work_field.field_name %></div>
		<div class="panel-body">
		  <p><%= job.description %></p>
		</div>
		<ul class="list-group">
		  <li class="list-group-item"><strong>Organization:</strong> <%= job.organization.name %></li>
		  <li class="list-group-item"><strong>Qualifiction:</strong> <%= job.degre.name_with_type %></li>
		  <li class="list-group-item"><strong>City:</strong> <%= job.city.name %></li>
		</ul>
	</div>
<% end %>

app/views/shared/_leftsidebar.html.erb
<br>
<% if user_signed_in? %>
	<div class="list-group">
		<span class="list-group-item active">
			<h4><b>Categories</b></h4>
			<% Degre.all.each do |degree| %>
		</span>
		<span class="list-group-item">
			<span class="badge"><%= link_to "04", degree, class: "badge" %></span>
			<%= link_to degree.name_with_type, degree %>
		</span>
			<% end %>
	</div>
<% end %>

app/views/shared/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
        <%= value %>
  </div>
<% end %>

app/views/shared/_notice_alert_info_success.html.erb
<% if alert %>
  <div class="alert alert-danger" role="alert"><%= alert %></div>
<% end %>
<% if notice %>
  <div class="alert alert-success" role="alert"><%= notice %></div>
<% end %>

app/views/shared/_userinfo.html.erb
<% @user.userinfos.each do |info| %>
	<p>
		<strong>Date of birth:</strong>
		<%= info.date_of_birth.strftime("%B %d, %Y") %>
	</p>

	<p>
		<strong>Gender:</strong>
		<%= info.gender %>
	</p>

	<p>
		<strong>Mobile:</strong>
		<%= info.mobile %>
	</p>

	<p>
		<strong>Address:</strong>
		<%= info.address %>
	</p>

<br>
<%= link_to 'Edit Profile', edit_user_userinfo_path(@user, info),
																															class: "btn btn-success" %>
<% end %>