config/routes.rb
Rails.application.routes.draw do

  root 	'pages#home'
 	get 	'pages/about'
  get 	'pages/contact'

  devise_for :users, :controllers => { :registrations => :registrations }

  resources :organizations
  resources :work_fields
  resources :degres
  resources :institutes
  resources :cities
  resources :users do
  	resources :userinfos
  	resources :educations
	  resources :experiences
  end
  resources :advertises do
  	resources :jobs
	end



end

app/models/advertise.rb
class Advertise < ActiveRecord::Base
  belongs_to :user
  has_many :jobs, dependent: :destroy

  has_attached_file :image, :styles => { :medium => "500x500" }, 
  																				:default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  
end

app/models/city.rb
class City < ActiveRecord::Base
	has_many :institutes
	has_many :jobs
end

app/models/degre.rb
class Degre < ActiveRecord::Base
	has_many :educations
	has_many :jobs
	
  def name_with_type
   "#{name} #{drege_type}"
  end
end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :user
  belongs_to :degre
  belongs_to :institute
  
  validates :division, 				presence: true
  validates :obtained_marks, 	presence: true
  validates :pass_year, 			presence: true
  validates :degre_id, 				presence: true
  validates :institute_id, 		presence: true
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :work_field
  belongs_to :user
  
  validates :work_type, 			presence: true
  validates :start_date, 			presence: true
  validates :end_date, 				presence: true
  validates :work_field_id, 	presence: true
end

app/models/institute.rb
class Institute < ActiveRecord::Base
  belongs_to :city
  has_many :educations
  
  def name_with_city
   "#{name} #{city.name}"
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :advertise
  belongs_to :work_field
  belongs_to :organization
  belongs_to :degre
  belongs_to :city
end

app/models/organization.rb
class Organization < ActiveRecord::Base
	has_many :jobs
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :userinfos
  has_many :educations
  has_many :experiences
  has_many :joblizeds


  has_attached_file :avatar, :styles => { :medium => "400x400>", :thumb => "100x100>" },
  																				:default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/userinfo.rb
class Userinfo < ActiveRecord::Base
  belongs_to :user
  validates :mobile, 		presence: true
  validates :address, 	presence: true
end

app/models/work_field.rb
class WorkField < ActiveRecord::Base
	has_many :experiences
	has_many :jobs
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: [:show, :edit, :update, :destroy]

  def index
    @experiences = Experience.all
  end

  def show
  end

  def new
    @experience = Experience.new
  end

  def edit
    @user = current_user
  end

  def create
  	@user = User.find(params[:user_id])
    @experience = @user.experiences.create(experience_params)
      if @experience.save
				redirect_to @user, notice: 'Experience was successfully added.'
      else
      	flash[:alert] = "Please fill all experience fields below..!"
        redirect_to @user
      end
  end

  def update
    @user = User.find(params[:user_id])
    @experience = @user.experiences.find(params[:id])
    if @experience.update(experience_params)
      redirect_to @user, notice: 'Experience was successfully updated.'
    else
      flash[:alert] = "Please fill all experience fields below..!"
      redirect_to @user
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experience_params
      params.require(:experience).permit(:work_type, :start_date, :end_date, :work_field_id, :user_id)
    end
end

app/helpers/advertises_helper.rb
module AdvertisesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/degres_helper.rb
module DegresHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="col-md-12 alert alert-error alert-danger">
    <div class="col-md pull-right">
    <button type="button" class="close" data-dismiss="alert">x</button>
    </div>
    <h3>#{pluralize(resource.errors.count, "error")} prohibited this user being saved:</h3>
      <div class="col-md-12">
      #{messages}
      </div>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/institutes_helper.rb
module InstitutesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/userinfos_helper.rb
module UserinfosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/experiences/_form.html.erb
<h2>Add Experience</h2>
<%= form_for([@user, @user.experiences.build]) do |f| %>

    <%= f.text_area :work_type, class: "form-control", placeholder: "Type of Work Experience" %>
   <div class="row">
    <div class="col-md-12">
    <%= f.collection_select(:work_field_id, WorkField.all, :id, :field_name,
    												{prompt: "Select Work Type"}, class: "form-control" ) %>
   </div>
   </div>

    <%= f.date_select(:start_date, start_year: 1990, order: [:day, :month, :year],
    																	prompt: { day: 'Start Date', month: 'Start Month', year: 'Start Year' }) %>
    <%= f.date_select(:end_date, start_year: 1990, order: [:day, :month, :year],
    																	prompt: { day: 'End Date', month: 'End Month', year: 'End Year' }) %>

    <%= f.submit "Add Experience", class: "btn btn-primary" %>

<% end %>

app/views/experiences/edit.html.erb
<h2>Edit Experience</h2>
<%= form_for([current_user, @experience]) do |f| %>

    <%= f.text_area :work_type, class: "form-control", placeholder: "Type of Work Experience" %>
   <div class="row">
    <div class="col-md-12">
    <%= f.collection_select(:work_field_id, WorkField.all, :id, :field_name,
                            {prompt: "Select Work Type"}, class: "form-control" ) %>
   </div>
   </div>

    <%= f.date_select(:start_date, start_year: 1990, order: [:day, :month, :year],
                                      prompt: { day: 'Start Date', month: 'Start Month', year: 'Start Year' }) %>
    <%= f.date_select(:end_date, start_year: 1990, order: [:day, :month, :year],
                                      prompt: { day: 'End Date', month: 'End Month', year: 'End Year' }) %>

    <%= f.submit "Add Experience", class: "btn btn-primary" %>

<% end %>

app/views/experiences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Experiences</h1>

<table>
  <thead>
    <tr>
      <th>Work type</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Work field</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @experiences.each do |experience| %>
      <tr>
        <td><%= experience.work_type %></td>
        <td><%= experience.start_date %></td>
        <td><%= experience.end_date %></td>
        <td><%= experience.work_field %></td>
        <td><%= experience.user %></td>
        <td><%= link_to 'Show', experience %></td>
        <td><%= link_to 'Edit', edit_experience_path(experience) %></td>
        <td><%= link_to 'Destroy', experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Experience', new_experience_path %>

app/views/experiences/new.html.erb
<h1>New Experience</h1>

<%= render 'form' %>

<%= link_to 'Back', experiences_path %>

app/views/experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Work type:</strong>
  <%= @experience.work_type %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @experience.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @experience.end_date %>
</p>

<p>
  <strong>Work field:</strong>
  <%= @experience.work_field %>
</p>

<p>
  <strong>User:</strong>
  <%= @experience.user %>
</p>

<%= link_to 'Edit', edit_experience_path(@experience) %> |
<%= link_to 'Back', experiences_path %>