config/routes.rb
Rails.application.routes.draw do

  root 	'pages#home'
 	get 	'pages/about'
  get 	'pages/contact'

  devise_for :users, :controllers => { :registrations => :registrations }

  resources :organizations
  resources :work_fields
  resources :degres
  resources :institutes
  resources :cities
  resources :users do
  	resources :userinfos
  	resources :educations
	  resources :experiences
  end
  resources :advertises do
  	resources :jobs
	end



end

app/models/advertise.rb
class Advertise < ActiveRecord::Base
  belongs_to :user
  has_many :jobs, dependent: :destroy

  has_attached_file :image, :styles => { :medium => "500x500" }, 
  																				:default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  
end

app/models/city.rb
class City < ActiveRecord::Base
	has_many :institutes
	has_many :jobs
end

app/models/degre.rb
class Degre < ActiveRecord::Base
	has_many :educations
	has_many :jobs
	
  def name_with_type
   "#{name} #{drege_type}"
  end
end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :user
  belongs_to :degre
  belongs_to :institute
  
  validates :division, 				presence: true
  validates :obtained_marks, 	presence: true
  validates :pass_year, 			presence: true
  validates :degre_id, 				presence: true
  validates :institute_id, 		presence: true
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :work_field
  belongs_to :user
  
  validates :work_type, 			presence: true
  validates :start_date, 			presence: true
  validates :end_date, 				presence: true
  validates :work_field_id, 	presence: true
end

app/models/institute.rb
class Institute < ActiveRecord::Base
  belongs_to :city
  has_many :educations
  
  def name_with_city
   "#{name} #{city.name}"
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :advertise
  belongs_to :work_field
  belongs_to :organization
  belongs_to :degre
  belongs_to :city
end

app/models/organization.rb
class Organization < ActiveRecord::Base
	has_many :jobs
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :userinfos
  has_many :educations
  has_many :experiences
  has_many :joblizeds


  has_attached_file :avatar, :styles => { :medium => "400x400>", :thumb => "100x100>" },
  																				:default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/userinfo.rb
class Userinfo < ActiveRecord::Base
  belongs_to :user
  validates :mobile, 		presence: true
  validates :address, 	presence: true
end

app/models/work_field.rb
class WorkField < ActiveRecord::Base
	has_many :experiences
	has_many :jobs
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :set_education, only: [:show, :edit, :update, :destroy]

  def index
    @educations = Education.all
  end

  def show
  end

  def new
    @education = Education.new
  end

  def edit
    @user = current_user
  end

  def create
  	@user = User.find(params[:user_id])
    @education = @user.educations.create(education_params)
      if @education.save
        redirect_to @user, notice: 'Education was successfully added.'
      else
      	flash[:alert] = "Please fill complete form below..!"
        redirect_to @user
      end
  end

  def update
    @user = User.find(params[:user_id])
    @education = @user.educations.find(params[:id])
    if @education.update(education_params)
      redirect_to @user, notice: 'Education was successfully updated.'
    else
      flash[:alert] = "Please fill complete form below..!"
      redirect_to @user
    end
  end

  private

    def set_education
      @education = Education.find(params[:id])
    end

    def education_params
      params.require(:education).permit(:division, :obtained_marks, :pass_year, :user_id, :degre_id, :institute_id)
    end
end

app/helpers/advertises_helper.rb
module AdvertisesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def logged_in_admin?
		current_user && User.find_by(email: "ghazi545@gmail.com") == current_user
	end
	
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/degres_helper.rb
module DegresHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="col-md-12 alert alert-error alert-danger">
    <div class="col-md pull-right">
    <button type="button" class="close" data-dismiss="alert">x</button>
    </div>
    <h3>#{pluralize(resource.errors.count, "error")} prohibited this user being saved:</h3>
      <div class="col-md-12">
      #{messages}
      </div>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/institutes_helper.rb
module InstitutesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/userinfos_helper.rb
module UserinfosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/educations/_form.html.erb
<h2>Add Education</h2>
<%= form_for([@user, @user.educations.build]) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
   <div class="row">
   <div class="col-md-6">
    <%= f.text_field :division, class: "form-control", placeholder: "Division or Grade" %>
   </div>
   <div class="col-md-6">
    <%= f.text_field :obtained_marks, class: "form-control", placeholder: "Obtained Marks" %>
   </div>
   </div>
   <div class="row">
    <%= f.date_select(:pass_year, start_year: 1985, discard_day: true, discard_month: true,
    																								prompt: "Select Year") %>
   <div class="col-md-4">
    <%= f.collection_select(:degre_id, Degre.all, :id, :name_with_type,
    												{prompt: "Select a Deree"}, class: "form-control") %>
    </div>
    <div class="col-md-4">
    <%= f.collection_select(:institute_id, Institute.all, :id, :name_with_city,
    												{prompt: "Select a Institute"}, class: "form-control") %>
		</div>
		</div>
    <%= f.submit "Submit", class: "btn btn-primary" %>

<% end %>

app/views/educations/edit.html.erb
<h2>Edit Education</h2>
<%= form_for([current_user, @education]) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
   <div class="row">
   <div class="col-md-6">
    <%= f.text_field :division, class: "form-control", placeholder: "Division or Grade" %>
   </div>
   <div class="col-md-6">
    <%= f.text_field :obtained_marks, class: "form-control", placeholder: "Obtained Marks" %>
   </div>
   </div>
   <div class="row">
    <%= f.date_select(:pass_year, start_year: 1985, discard_day: true, discard_month: true,
                                                    prompt: "Select Year") %>
   <div class="col-md-4">
    <%= f.collection_select(:degre_id, Degre.all, :id, :name_with_type,
                            {prompt: "Select a Deree"}, class: "form-control") %>
    </div>
    <div class="col-md-4">
    <%= f.collection_select(:institute_id, Institute.all, :id, :name_with_city,
                            {prompt: "Select a Institute"}, class: "form-control") %>
    </div>
    </div>
    <%= f.submit "Update", class: "btn btn-primary" %>

<% end %>

app/views/educations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Educations</h1>

<table>
  <thead>
    <tr>
      <th>Division</th>
      <th>Obtained marks</th>
      <th>Pass year</th>
      <th>User</th>
      <th>Degre</th>
      <th>Institute</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @educations.each do |education| %>
      <tr>
        <td><%= education.division %></td>
        <td><%= education.obtained_marks %></td>
        <td><%= education.pass_year %></td>
        <td><%= education.degre.name %></td>
        <td><%= education.institute.name %></td>
        <td><%= link_to 'Show', education %></td>
        <td><%= link_to 'Edit', edit_education_path(education) %></td>
        <td><%= link_to 'Destroy', education, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Education', new_education_path %>

app/views/educations/new.html.erb
<h1>New Education</h1>

<%= render 'form' %>

app/views/educations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Division:</strong>
  <%= @education.division %>
</p>

<p>
  <strong>Obtained marks:</strong>
  <%= @education.obtained_marks %>
</p>

<p>
  <strong>Pass year:</strong>
  <%= @education.pass_year %>
</p>

<p>
  <strong>Degre:</strong>
  <%= @education.degre.name %>
</p>

<p>
  <strong>Institute:</strong>
  <%= @education.institute.name %>
</p>

<%= link_to 'Edit', edit_education_path(@education) %> |
<%= link_to 'Back', educations_path %>