config/routes.rb
Rails.application.routes.draw do

  root 	'pages#home'
 	get 	'pages/about'
  get 	'pages/contact'

  devise_for :users, :controllers => { :registrations => :registrations }

  resources :organizations
  resources :work_fields
  resources :degres
  resources :institutes
  resources :cities
  resources :users do
  	resources :userinfos
  	resources :educations
	  resources :experiences
  end
  resources :advertises do
  	resources :jobs
	end



end

app/models/advertise.rb
class Advertise < ActiveRecord::Base
  belongs_to :user
  has_many :jobs, dependent: :destroy

  has_attached_file :image, :styles => { :medium => "500x500" }, 
  																				:default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  
end

app/models/city.rb
class City < ActiveRecord::Base
	has_many :institutes
	has_many :jobs
end

app/models/degre.rb
class Degre < ActiveRecord::Base
	has_many :educations
	has_many :jobs
	
  def name_with_type
   "#{name} #{drege_type}"
  end
end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :user
  belongs_to :degre
  belongs_to :institute
  
  validates :division, 				presence: true
  validates :obtained_marks, 	presence: true
  validates :pass_year, 			presence: true
  validates :degre_id, 				presence: true
  validates :institute_id, 		presence: true
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :work_field
  belongs_to :user
  
  validates :work_type, 			presence: true
  validates :start_date, 			presence: true
  validates :end_date, 				presence: true
  validates :work_field_id, 	presence: true
end

app/models/institute.rb
class Institute < ActiveRecord::Base
  belongs_to :city
  has_many :educations
  
  def name_with_city
   "#{name} #{city.name}"
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :advertise
  belongs_to :work_field
  belongs_to :organization
  belongs_to :degre
  belongs_to :city
end

app/models/organization.rb
class Organization < ActiveRecord::Base
	has_many :jobs
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :userinfos
  has_many :educations
  has_many :experiences
  has_many :joblizeds


  has_attached_file :avatar, :styles => { :medium => "400x400>", :thumb => "100x100>" },
  																				:default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/userinfo.rb
class Userinfo < ActiveRecord::Base
  belongs_to :user
  validates :mobile, 		presence: true
  validates :address, 	presence: true
end

app/models/work_field.rb
class WorkField < ActiveRecord::Base
	has_many :experiences
	has_many :jobs
end

app/controllers/degres_controller.rb
class DegresController < ApplicationController
  before_action :set_degre, only: [:show, :edit, :update, :destroy]
  before_filter :admin

  def index
    @degres = Degre.all
    @user = current_user
  end

  def show
  	@user = current_user
  end

  def new
    @degre = Degre.new
    @user = current_user
  end

  def edit
  end

  def create
    @degre = Degre.new(degre_params)

    respond_to do |format|
      if @degre.save
        format.html { redirect_to @degre, notice: 'Degre was successfully created.' }
        format.json { render :show, status: :created, location: @degre }
      else
        format.html { render :new }
        format.json { render json: @degre.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @degre.update(degre_params)
        format.html { redirect_to @degre, notice: 'Degre was successfully updated.' }
        format.json { render :show, status: :ok, location: @degre }
      else
        format.html { render :edit }
        format.json { render json: @degre.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @degre.destroy
    respond_to do |format|
      format.html { redirect_to degres_url, notice: 'Degre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_degre
      @degre = Degre.find(params[:id])
    end

    def degre_params
      params.require(:degre).permit(:name, :drege_type)
    end

    def admin
    	@user = current_user
     unless current_user && User.find_by(email: "ghazi545@gmail.com") == current_user
      flash[:alert] = 'Access denied..! Please login as admin.'
      redirect_to @user
     end
    end
end

app/helpers/advertises_helper.rb
module AdvertisesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def logged_in_admin?
		current_user && User.find_by(email: "ghazi545@gmail.com") == current_user
	end
	
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/degres_helper.rb
module DegresHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="col-md-12 alert alert-error alert-danger">
    <div class="col-md pull-right">
    <button type="button" class="close" data-dismiss="alert">x</button>
    </div>
    <h3>#{pluralize(resource.errors.count, "error")} prohibited this user being saved:</h3>
      <div class="col-md-12">
      #{messages}
      </div>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/institutes_helper.rb
module InstitutesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/userinfos_helper.rb
module UserinfosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/degres/_form.html.erb
<%= form_for(@degre) do |f| %>
  <% if @degre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@degre.errors.count, "error") %> prohibited this degre from being saved:</h2>

      <ul>
      <% @degre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :drege_type %><br>
    <%= f.text_field :drege_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/degres/edit.html.erb
<h1>Editing Degre</h1>

<%= render 'form' %>

<%= link_to 'Show', @degre %> |
<%= link_to 'Back', degres_path %>

app/views/degres/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listing Degrees</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Drege type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @degres.each do |degre| %>
      <tr>
        <td><%= degre.name %></td>
        <td><%= degre.drege_type %></td>
        <td><%= link_to 'Show', degre, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_degre_path(degre), class: "btn btn-info" %></td>
        <td><%= link_to 'Destroy', degre, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Degre', new_degre_path %>

app/views/degres/new.html.erb
<h1>New Degre</h1>

<%= render 'form' %>

<%= link_to 'Back', degres_path %>

app/views/degres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @degre.name %>
</p>

<p>
  <strong>Drege type:</strong>
  <%= @degre.drege_type %>
</p>

<%= link_to 'Edit', edit_degre_path(@degre) %> |
<%= link_to 'Back', degres_path %>